version: '3.3'

services:

  web:
    image: odoo:18
    container_name: odoo_web
    depends_on:
      - db
    ports:
      - 8077:8069
    volumes:
      - ./volumesOdoo/addons:/mnt/extra-addons
      - ./volumesOdoo/odoo/filestore:/var/lib/odoo/filestore
      - ./volumesOdoo/odoo/sessions:/var/lib/odoo/sessions
    user: root
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all 

  db:
    image: postgres:15
    container_name: odoo_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./volumesOdoo/dataPostgreSQL:/var/lib/postgresql/data
